### ISSUE TITLE
Multiple relations

### ISSUE THREAD

**Issue by AshwinParanjape** [arunchaganty/kbp-online#6]
What is the protocol for multiple possible relations and how do we implement it. 
For instance "But Romanian Prime Minister Victor Ponta", VP works for R, very likely lives in R and it is possible to deduce he was born there. Do we instruct them to choose the best representative (or pick a relation only if it is explicit and err on the side of precision than recall) or do we allow multiple relations to be selected.

**Comment by arunchaganty** [comment]
So, I think we've agreed that this is currently beyond the scope our current annotations. We may revisit this in the future.
